/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'on-background': 'var(--st-on-background)',
        'on-secondary-container': 'var(--st-on-secondary-container)',
        secondary: 'var(--st-secondary)',
        'secondary-fixed-dim': 'var(--st-secondary-fixed-dim)',
        'surface-container-low': 'var(--st-surface-container-low)',
        primary: 'var(--st-primary)',
        'secondary-fixed': 'var(--st-secondary-fixed)',
        outline: 'var(--st-outline)',
        'secondary-container': 'var(--st-secondary-container)',
        tertiary: 'var(--st-tertiary)',
        'surface-tint': 'var(--st-surface-tint)',
        'on-tertiary-container': 'var(--st-on-tertiary-container)',
        'on-secondary-fixed': 'var(--st-on-secondary-fixed)',
        background: 'var(--st-background)',
        'on-surface-variant': 'var(--st-on-surface-variant)',
        error: 'var(--st-error)',
        'error-container': 'var(--st-error-container)',
        'tertiary-fixed-dim': 'var(--st-tertiary-fixed-dim)',
        'surface-variant': 'var(--st-surface-variant)',
        'on-primary': 'var(--st-on-primary)',
        'surface-bright': 'var(--st-surface-bright)',
        'surface-container-high': 'var(--st-surface-container-high)',
        'inverse-on-surface': 'var(--st-inverse-on-surface)',
        'surface-container-lowest': 'var(--st-surface-container-lowest)',
        'inverse-primary': 'var(--st-inverse-primary)',
        'tertiary-fixed': 'var(--st-tertiary-fixed)',
        'on-secondary-fixed-variant': 'var(--st-on-secondary-fixed-variant)',
        'surface-dim': 'var(--st-surface-dim)',
        'on-secondary': 'var(--st-on-secondary)',
        'surface-container-highest': 'var(--st-surface-container-highest)',
        'primary-fixed': 'var(--st-primary-fixed)',
        'on-error-container': 'var(--st-on-error-container)',
        'tertiary-container': 'var(--st-tertiary-container)',
        'on-surface': 'var(--st-on-surface)',
        'inverse-surface': 'var(--st-inverse-surface)',
        'on-error': 'var(--st-on-error)',
        'primary-fixed-dim': 'var(--st-primary-fixed-dim)',
        'surface-container': 'var(--st-surface-container)',
        'primary-container': 'var(--st-primary-container)',
        'outline-variant': 'var(--st-outline-variant)',
        'on-primary-container': 'var(--st-on-primary-container)',
        'on-primary-fixed': 'var(--st-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--st-on-primary-fixed-variant)',
        'on-tertiary-fixed-variant': 'var(--st-on-tertiary-fixed-variant)',
        'on-tertiary': 'var(--st-on-tertiary)',
        surface: 'var(--st-surface)',
        'on-tertiary-fixed': 'var(--st-on-tertiary-fixed)',
        success: 'var(--st-success)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        gutter: '16px',
        xl: '32px',
        xs: '8px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        md: '16px',
        base: '4px',
        sm: '12px',
      },
      fontFamily: {
        'data-mono': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        sans: ['Inter', 'Segoe UI', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        stitch: '0 4px 20px rgba(15, 23, 42, 0.05)',
        'stitch-lg': '0 8px 32px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [],
};
